---
title: "Gas_price_adjustment_CPFV"
author: "Van Deusen"
date: "2024-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(FishLife)
library(freeR)
library(dplyr)
library(janitor)
library(ggplot2)
library(lubridate)
library(sf)
library(tidyr)
library(viridis)
library(quantmod) 
library(egg)
library(ggspatial)
path_out= "C:/Users/vanessa.van.deusen/Desktop/Van.Deusen_Local/CPFV_local/Data/Predictor_Datasets"
```

## Importing data
```{r cars}
CPIAUCSL<-read_csv("C:/Users/vanessa.van.deusen/Desktop/Van.Deusen_Local/CPFV_local/Data/Predictor_Datasets/Raw/CPIAUCSL_1.23.26_80to25_seasonallyadjusted.csv")

gas_prices<-read_csv("C:/Users/vanessa.van.deusen/Desktop/Van.Deusen_Local/CPFV_local/Data/Predictor_Datasets/Raw/Gas_unleaded_reg_per_gallon_US_city_avg.csv")
```

#Formatting Consumer Price Index
```{r}
#Cleaning
CPIAUCSL_df <- CPIAUCSL %>%
  mutate(
    DATE  = ymd(observation_date),
    Year  = year(DATE),
    Month = month(DATE)
  ) %>%
  select(-1)

#Pulling December 2025 CPI
dec_2025_val <- CPIAUCSL_df %>%
  filter(Year == 2025, Month == 12) %>%
  pull(CPIAUCSL)

#Calculating Adjustment factor relative to December 2025
CPIAUCSL_df<-CPIAUCSL_df %>% 
  mutate(adjust25dec = dec_2025_val/CPIAUCSL)


#Formatting gas prices 
##removing non data rows in R 
###Remove unnecessary ID column
gas_prices_formatted <- gas_prices %>%
  select(-1)%>% #Remove first column
  rename(Month = Period, 
         Gas_Price_USD = Value) %>%               # Rename Period to Month
  mutate(Month = str_remove(Month, "M"),   # Remove the "M"
         Month = as.numeric(Month), 
         Year= as.numeric(Year))
  

#Adjusting for inflation
gas_adjusted<-left_join(gas_prices_formatted, 
                        CPIAUCSL_df, 
                        by= c("Year","Month"),
                        relationship = "one-to-one", 
                        na_matches = "never")


gas_adjusted$adjust_price<-gas_adjusted$Gas_Price_USD*gas_adjusted$adjust25dec
```

##Exporting
```{r}

write.csv(gas_adjusted,file.path(path_out, "gas_adjusted2025.csv"))
```